// ─── MENU DATA ────────────────────────────────────────────────────────────────
// Replace `image` URLs with your actual Unsplash / CDN URLs before deploying.

export const MENU_CATEGORIES = [
  "All",
  "West African",
  "Fast Food",
  "Grills & Wraps",
  "Sides",
  "Drinks",
  "Desserts",
];

export const MENU_ITEMS = [
  // ── West African ─────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Jollof Rice",
    category: "West African",
    price: 35,
    description: "Party-style smoky Jollof rice with your choice of protein.",
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&q=80",
    popular: true,
    spicy: false,
  },
  {
    id: 2,
    name: "Fried Rice",
    category: "West African",
    price: 35,
    description: "Fragrant fried rice tossed with vegetables and egg.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
    popular: false,
    spicy: false,
  },
  {
    id: 3,
    name: "Assorted Jollof & Fried Rice",
    category: "West African",
    price: 45,
    description: "Half Jollof, half Fried Rice — best of both worlds.",
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&q=80",
    popular: true,
    spicy: false,
  },
  {
    id: 4,
    name: "Banku with Tilapia",
    category: "West African",
    price: 55,
    description: "Fermented corn & cassava dough served with grilled whole Tilapia and spicy pepper.",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",
    popular: true,
    spicy: true,
  },
  // ── Fast Food ────────────────────────────────────────────────────────────
  {
    id: 5,
    name: "Classic Burger",
    category: "Fast Food",
    price: 50,
    description: "Juicy beef patty, lettuce, tomato, pickles, and our secret sauce in a brioche bun.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    popular: true,
    spicy: false,
  },
  {
    id: 6,
    name: "Double Smash Burger",
    category: "Fast Food",
    price: 65,
    description: "Two smash patties, double cheese, caramelized onions.",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&q=80",
    popular: false,
    spicy: false,
  },
  {
    id: 7,
    name: "Pizza (Margherita)",
    category: "Fast Food",
    price: 70,
    description: "Hand-stretched dough, San Marzano tomato, fresh mozzarella, basil.",
    image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&q=80",
    popular: false,
    spicy: false,
  },
  {
    id: 8,
    name: "Pepperoni Pizza",
    category: "Fast Food",
    price: 80,
    description: "Loaded with spicy pepperoni and stretchy mozzarella.",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80",
    popular: true,
    spicy: true,
  },
  // ── Grills & Wraps ──────────────────────────────────────────────────────
  {
    id: 9,
    name: "Chicken Shawarma",
    category: "Grills & Wraps",
    price: 40,
    description: "Marinated chicken, garlic sauce, pickled veggies, wrapped in soft flatbread.",
    image: "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=600&q=80",
    popular: true,
    spicy: false,
  },
  {
    id: 10,
    name: "Beef Shawarma",
    category: "Grills & Wraps",
    price: 50,
    description: "Slow-cooked beef strips, tahini, tomatoes, and crispy onions.",
    image: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=600&q=80",
    popular: false,
    spicy: false,
  },
  // ── Sides ────────────────────────────────────────────────────────────────
  {
    id: 11,
    name: "French Fries",
    category: "Sides",
    price: 20,
    description: "Golden crispy fries seasoned with our house spice blend.",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&q=80",
    popular: false,
    spicy: false,
  },
  {
    id: 12,
    name: "Loaded Fries",
    category: "Sides",
    price: 35,
    description: "Fries topped with melted cheese, jalapeños, beef mince, and sour cream.",
    image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&q=80",
    popular: true,
    spicy: true,
  },
  // ── Drinks ──────────────────────────────────────────────────────────────
  {
    id: 13,
    name: "Caffé Latte",
    category: "Drinks",
    price: 25,
    description: "Smooth espresso with steamed milk. Served hot or iced.",
    image: "https://images.unsplash.com/photo-1534778101976-62847782c213?w=600&q=80",
    popular: false,
    spicy: false,
  },
  {
    id: 14,
    name: "Sobolo (Hibiscus Drink)",
    category: "Drinks",
    price: 15,
    description: "Chilled Ghanaian hibiscus drink with ginger and cloves.",
    image: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=600&q=80",
    popular: true,
    spicy: false,
  },
  {
    id: 15,
    name: "Fresh Fruit Juice",
    category: "Drinks",
    price: 18,
    description: "Blended seasonal fruits — ask your server what's fresh today.",
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&q=80",
    popular: false,
    spicy: false,
  },
  // ── Desserts ─────────────────────────────────────────────────────────────
  {
    id: 16,
    name: "Stella's Layer Cake",
    category: "Desserts",
    price: 30,
    description: "Rich vanilla sponge layered with chocolate ganache and cream.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
    popular: true,
    spicy: false,
  },
];
